general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

# toggle keyboard lights after 1 minute
listener {
    timeout = 60
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# toggle screen brightness after 3 minutes
listener {
    timeout = 180
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# lock session after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# toggle screen after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

# suspend system after 12 minutes
listener {
    timeout = 720
    on-timeout = systemctl suspend
}
